config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'

  # Provides all RESTful routes
  resources :articles
  resources :users, except: [:new]
  resources :categories

  # Provides all non-RESTful routes
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :content, presence: true, length: { minimum: 10, maximum: 10_000 }
end

app/models/article_category.rb
# frozen_string_literal: true

class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  VALID_USERNAME = /\A[a-zA-Z0-9]+\Z/
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 },
                       format: { with: VALID_USERNAME }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :about, presence: true,
                    length: { maximum: 150 }
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'You must be logged in to perform this action'
    redirect_to login_path
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :find_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def show; end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def update
    if @article.update(article_params_whitelist)
      flash[:notice] = 'Article was updated successfully'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def create
    @article = Article.new(article_params_whitelist)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to @article
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params_whitelist
    params.require(:article).permit(:title, :content, category_ids: [])
  end

  def require_same_user
    return unless current_user != @article.user && !current_user.admin?

    flash[:alert] = 'You are not the author of this post.'
    redirect_to @article
  end
end

# We are using @ to make instance variables so that they can be accessed by the views.

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update show destroy]
  before_action :require_admin, except: %i[index show]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params_whitelist)
    if @category.save
      flash[:notice] = 'Category successfully created.'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params_whitelist)
      flash[:notice] = 'Category name changed successfully'
      redirect_to @category
    else
      render 'edit'
    end
  end

  def edit; end

  def destroy
    @category.destroy
    flash[:notice] = 'The category has been successfully deleted.'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params_whitelist
    params.require(:category).permit(:name)
  end

  def require_admin
    return if logged_in? && current_user.admin?

    flash[:alert] = 'This action requires administrator permissions'
    redirect_to categories_path
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

before_action :set_user_session, only: %i[create]

class SessionsController < ApplicationController
  def new; end

  def create
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "You're in!"
      redirect_to user
    else
      flash.now[:alert] = 'Wrong credentials.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

private

def set_session_user
  user = User.find_by(email: params[:session][:email].downcase)
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update require_same_user]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params_whitelist)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] =
        "Welcome to the blog, #{@user.username}! You have succesfully registered and are ready to start writing."
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params_whitelist)
      flash[:notice] = 'Your profile was successfully updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'The account and its posts have been successfully deleted.'
    redirect_to @user
  end

  private

  def user_params_whitelist
    params.require(:user).permit(:username, :email, :about, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    return unless current_user != @user && !current_user.admin?

    flash[:alert] = 'You can only edit or delete your own account'
    redirect_to @user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article|%>
  <div class="mt-4">
    <div class="card text-center">
      <div class="card-header font-italic">
        <% if article.user %>
          by <%= link_to article.user.username, user_path(article.user)%>
        <% end %>
        <% if article.categories.any? %>
          <div>
            <%= render article.categories %>
          </div>
        <% end %>
      </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
      <div class="card-text"><%= truncate(simple_format(article.content), escape: false, length: 100) %></div>
      <%= link_to "Read", article_path(article), class: "btn btn-outline-warning"%>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-warning ml-2"%>
        <%= link_to "Delete", article_path(article), class: "btn btn-outline-warning ml-2", method: :delete, data: {confirm: "Are you sure?"}%>
      <% end %>
    </div>
    <div class="card-footer">
      <small>Written <%= time_ago_in_words(article.created_at)%> ago</small>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>
<div class="container">
  <div class="row justify-content-center p-4">
    <div class="col-10">
      <%= form_with(model: @article, local: true) do |f|%>
        <div class="form-group row mt-2">
          <%= f.label :title, class: "col-3 col-form-label"%>
          <div class="col-8">
            <%= f.text_field :title, class: "form-control bg-custom-dark text-custom-light", placeholder: "Title of the article"%>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :content, class: "col-3 col-form-label"%>
          <div class="col-8">
            <%= f.text_area :content, rows: 10, class: "form-control bg-custom-dark text-custom-light", placeholder: "Content of the article"%>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :category, class: "col-3 col-form-label"%>
          <div class="col-8">
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
                                    { prompt: "Select categories" }, { multiple: true, size: 4,
                                     class: "custom-select form-control bg-custom-dark text-custom-light" }) %>
          </div>
        </div>        
        <div class="form-group text-center">
          <%= f.submit "Publish", class: "btn btn-outline-warning"%>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Actually... nevermind that. ]', articles_path, class: "text-center text-warning w-auto"%>
  </div>
</div>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit Article</title>
</head>
<body id="page-content">
  <h1 class="text-center text-warning pt-4">Let's revamp this post!</h1>
  <%= render 'form'%>
</body>
</html>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Index</title>
</head>
<body id="page-content">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
      <div class="mt-4">
      <h1 class="text-center text-warning m-4">The Articles</h1>
        <% if logged_in? %>
          <%= link_to "The secret of getting ahead is getting started", new_article_path, class: "btn btn-outline-warning btn-block" %>
        <% else %>
          <%= link_to "The secret of getting ahead is getting started", signup_path, class: "btn btn-outline-warning btn-block" %>
        <% end %>
      </div>
        <div class="flickr_pagination mt-4">
          <%= will_paginate @articles, :container => false %>
        </div>
        <%= render 'article' %>
        <div class="flickr_pagination m-4">
          <%= will_paginate @articles, :container => false %>
        </div>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Article</title>
</head>
<body id="page-content">
  <h1 class="text-center text-warning pt-4">Let's get writing</h1>
  <%= render 'form'%>
</body>
</html>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body id="page-content">
  <h2 class="text-center mt-4 text-custom-light"><%= @article.title%></h2>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="mt-4">
          <div class="card text-center">
            <div class="card-header font-italic">
              <%= @article.user.username %>
              <% if @article.categories.any? %>
                <div>
                  <%= render @article.categories %>
                </div>
              <% end %>
            </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.content) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-warning"%>
              <%= link_to "Delete", article_path(@article), class: "btn btn-outline-warning", method: :delete, data: {confirm: "Are you sure?"}%>
            <% end %>
          </div>
          <div class="card-footer">
            <small>Written <%= time_ago_in_words(@article.created_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/categories/_categories.html.erb
<% @categories.each do |category|%>
  <div class="mt-4">
    <div class="card text-center">
    <div class="card-body">
      <h5 class="card-title-category"><%= link_to category.name, category_path(category) %></h5>
      <div class="card-text"><%= pluralize(category.articles.count, "post") %></div><br>
      <% if logged_in? && current_user.admin? %>
        <%= link_to "Edit", edit_category_path(category), class: "btn btn-outline-warning m-2"%>
        <%= link_to "Delete", category_path(category), class: "btn btn-outline-warning m-2", method: :delete, data: {confirm: "Are you sure?"}%>
      <% end %>
    </div>
    <div class="card-footer">
      <small>Created <%= time_ago_in_words(category.created_at)%> ago</small>
    </div>
  </div>
<% end %>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge mr-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category%>
<div class="container">
  <div class="row justify-content-center p-4">
    <div class="col-10">
      <%= form_with(model: @category, local: true) do |f|%>
        <div class="form-group row mt-2">
          <%= f.label :name, class: "col-3 col-form-label"%>
          <div class="col-8">
            <%= f.text_field :name, class: "form-control bg-custom-dark text-custom-light", placeholder: "Enter category name"%>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit class: "btn btn-outline-warning"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit a category</title>
</head>
<body id="page-content">
  <h1 class="text-center text-warning pt-4">Edit category</h1>
  <%= render 'form'%>
</body>
</html>

app/views/categories/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Categories</title>
</head>
<body id="page-content">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <h1 class="text-center text-warning m-4">The Categories</h1>
        <div class="flickr_pagination mt-4">
          <%= will_paginate @categories, :container => false %>
        </div>
        <% if logged_in? && current_user.admin? %>
          <%= link_to "Create new category", new_category_path, class: "btn btn-outline-warning btn-block" %>
        <% end %>
        <%= render 'categories' %>
        <div class="flickr_pagination m-4">
          <%= will_paginate @categories, :container => false %>
        </div>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/categories/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create a new category</title>
</head>
<body id="page-content">
  <h1 class="text-center text-warning pt-4">Create a new category</h1>
  <%= render 'form'%>
</body>
</html>

app/views/categories/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category</title>
  </head>
  <body id="page-content">
    <h1 class="text-center text-warning mt-4"><%= @category.name %></h1>
    <% if logged_in? && current_user.admin? %>
      <div class="text-center mt-4">
        <%= link_to "Rename category", edit_category_path(@category), class: "btn btn-outline-warning mr-4" %>
        <%= link_to "Delete category", category_path(@category), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
    <div class="flickr_pagination m-4">
      <%= will_paginate @articles, :container => false %>
    </div>
    <h5 class="text-center text-custom-light">Related Posts</h5>
    <div class="container">
      <%= render 'articles/article' %>
    </div>
    <div class="flickr_pagination m-4">
      <%= will_paginate @articles, :container => false %>
    </div>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 fixed-bottom">
  <div class="container text-center">
    <span class="text-muted"><small>Copyright <%= link_to "parK-dev", "https://github.com/parK-dev", class: "text-muted"%> </small>
    </span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg|%>
      <% if name == "notice"%>
        <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% else %>
        <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>        
    <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to "parK", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Writers", users_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link"%>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
              <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
        <% end %>
        <% if logged_in? && current_user.admin? %>
          <li class="nav-item">
            <%= link_to "Admin", users_path, class: "nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
      <ul class="navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="nav-item text-nowrap">
            <%= link_to 'Log out', logout_path, method: :delete %>
          </li>
        <% else %>
          <li class="nav-item mr-4 text-nowrap">
            <%= link_to 'Log In', login_path %>
          </li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang= "en">
  <head>
    <title>parKblog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
    <%= render 'layouts/footer'%>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
</head>
<body id="home-bg">
  <div class="jumbotron-home text-center">
    <h1 class="display-4">parK Blog</h1>
    <p class="lead">You can make anything by writing</p>
    <hr class="my-4">
    <p>Start before you're ready</p>
    <%= link_to "Sign up!", signup_path, class: "btn btn-secondary btn-lg" %>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<div class="container">
  <% if obj.errors.any?%>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved: </h4>
    <ul>
      <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>
<div class="container">
  <div class="row justify-content-center p-4">
    <div class="col-10">
      <%= form_with(model: @user, local: true) do |f|%>
        <div class="form-group row mt-2">
          <%= f.label :username, class: "col-3 col-form-label"%>
          <div class="col-8">
            <%= f.text_field :username, class: "form-control bg-custom-dark text-custom-light", placeholder: "Enter a username"%>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :about, class: "col-3 col-form-label"%>
          <div class="col-8">
            <%= f.text_area :about, rows: 5, class: "form-control bg-custom-dark text-custom-light", placeholder: "Tell us about yourself"%>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: "col-3 col-form-label"%>
          <div class="col-8">
            <%= f.email_field :email, class: "form-control bg-custom-dark text-custom-light", placeholder: "Enter your email"%>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :password, class: "col-3 col-form-label"%>
          <div class="col-8">
            <%= f.password_field :password, class: "form-control bg-custom-dark text-custom-light", placeholder: "Enter a secure password"%>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit(@user.new_record? ? "Sign me up!" : "Save profile", class: "btn btn-outline-warning")%>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Actually... nevermind that. ]', articles_path, class: "text-center text-warning w-auto"%>
  </div>
</div>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit User</title>
</head>
<body id="page-content">
  <h1 class="text-center text-warning pt-4">Let's work on your profile</h1>
  <%= render 'form'%>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User Index</title>
</head>
<body id="page-content">
  <h1 class="text-center text-warning mt-4">The Writers</h1>
  <div class="flickr_pagination m-4">
    <%= will_paginate @users, :container => false %>
  </div>
  <div class="container">
    <% @users.each do |user|%>
    <div class="mt-4">
      <div class="card text-center">
        <div class="card-header font-italic">
          <%= user.username %>
        </div>
      <div class="card-body">
        <h5 class="card-title"><%= user.about %></h5>
        <div class="card-text"><%= pluralize(user.articles.count, "post") %></div><br>
        <%= link_to "View profile", user, class: "btn btn-outline-warning"%>
          <% if logged_in? && (user == current_user || current_user.admin?) %>
            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-warning ml-2"%>
          <% end %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Delete profile", user_path(user), class: "btn btn-outline-danger ml-2", method: :delete,
            data: { confirm: "Are you sure you want to delete this account and all its posts?"}%>
          <% end %>     
      </div>
      <div class="card-footer">
        <small>Joined <%= time_ago_in_words(user.created_at)%> ago</small>
      </div>
    </div>
  <% end %>
  </div>
  <div class="flickr_pagination m-4">
    <%= will_paginate @users, :container => false %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New User</title>
</head>
<body id="page-content">
  <h1 class="text-center text-warning pt-4">Let's get you started</h1>
  <%= render 'form'%>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User Profile</title>
</head>
<body id="page-content">
  <h1 class="text-center text-warning pt-4"><%= @user.username %></h1>
  <h5 class="text-center text-custom-light pt-2"><%= @user.about %></h5>
  <% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
      <%= link_to "Rework my profile", edit_user_path(@user), class: "btn btn-outline-warning mr-4" %>
      <%= link_to "Delete my profile", user_path(@user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
  <div class="flickr_pagination m-4">
    <%= will_paginate @articles, :container => false %>
  </div>
  <h5 class="text-center text-custom-light">Blog Posts</h5>
  <div class="container">
    <%= render 'articles/article' %>
  </div>
  <div class="flickr_pagination m-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</body>
</html>